file /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/genesis
cd /local_home/local_home/hugo/genesis/scripts/network
break main
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/device
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/hines
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/newconn
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/olf
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/out
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/segment
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/shell
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/sim
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/sys
directory /local_home/local_home/hugo/genesis/source/uname/Linux/snapshots/san-antonio-1/tools
run TUTORIAL.g 
